set(TIC_TAC_TOE_INCLUDE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Include")
set(TIC_TAC_TOE_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Source/Library")
set(BOOST_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/boost_1_72_0/include/")
set(BOOST_DEBUG_PATH "${PROJECT_BINARY_DIR}/Dependencies/boost_1_72_0/lib")
set(BOOST_OPTIMIZED_PATH "${PROJECT_BINARY_DIR}/Dependencies/boost_1_72_0/lib")
set(BOOST_CHRONO_LIBRARY_DEBUG_PATH "${BOOST_DEBUG_PATH}/libboost_chrono.a")
set(BOOST_CHRONO_LIBRARY_OPTIMIZED_PATH
  "${BOOST_OPTIMIZED_PATH}/libboost_chrono.a")
set(BOOST_CONTEXT_LIBRARY_DEBUG_PATH "${BOOST_DEBUG_PATH}/libboost_context.a")
set(BOOST_CONTEXT_LIBRARY_OPTIMIZED_PATH
  "${BOOST_OPTIMIZED_PATH}/libboost_context.a")
set(BOOST_DATE_TIME_LIBRARY_DEBUG_PATH
  "${BOOST_DEBUG_PATH}/libboost_date_time.a")
set(BOOST_DATE_TIME_LIBRARY_OPTIMIZED_PATH
  "${BOOST_OPTIMIZED_PATH}/libboost_date_time.a")
set(BOOST_SYSTEM_LIBRARY_DEBUG_PATH "${BOOST_DEBUG_PATH}/libboost_system.a")
set(BOOST_SYSTEM_LIBRARY_OPTIMIZED_PATH
  "${BOOST_OPTIMIZED_PATH}/libboost_system.a")
set(BOOST_THREAD_LIBRARY_DEBUG_PATH "${BOOST_DEBUG_PATH}/libboost_thread.a")
set(BOOST_THREAD_LIBRARY_OPTIMIZED_PATH
  "${BOOST_OPTIMIZED_PATH}/libboost_thread.a")
